export default  {
    ADD_USER: 'ADD_USER',
    DELETE_NOTE: 'DELETE_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
  
    SET_INPUT_EMAIL: 'SET_INPUT_EMAIL',
    SET_INPUT_NAME: "SET_INPUT_NAME",
    SET_INPUT_PASSWORD: 'SET_INPUT_PASSWORD',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',
  }