export default  {
    ADD_USER: 'ADD_USER',
    DELETE_NOTE: 'DELETE_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
  

    SET_INPUT_DATEBORN: 'SET_INPUT_DATEBORN',
    SET_INPUT_MONTHBORN: 'SET_INPUT_MONTHBORN',
    SET_INPUT_YAERBORN: 'SET_INPUT_YAERBORN',
    SET_INPUT_CEP: 'SET_INPUT_CEP',
    SET_INPUT_CPF: 'SET_INPUT_CPF',
    SET_INPUT_ADRESS: 'SET_INPUT_ADRESS',
    SET_INPUT_REFERENCE: 'SET_INPUT_REFERENCE',
    SET_INPUT_CITY: 'SET_INPUT_CITY',
    SET_INPUT_COUTRY: 'SET_INPUT_COUTRY',
    SET_INPUT_EMAIL: 'SET_INPUT_EMAIL',
    SET_INPUT_NAME: "SET_INPUT_NAME",
    SET_INPUT_PASSWORD: 'SET_INPUT_PASSWORD',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',
  }

